---
output: github_document
---

## D1 distributions 

State the number of observations: 706

List the variables: 
- Annual Earnings Post Graduation 
- School Type: Public and Private
- School Student Demographic: High ACT & High Need, High ACT & Low Need, Low ACT & High Need, Low ACT & Low Need

State the graph type: Strip Plot

Explain why the graph type is suited to the data structure:  

- Since there is not a huge number of observations, a strip plot depicts the actual data.
- There are four clear categories, and the reader will want to compare them, which is easily done with the common x-axis.

Explain each design choice and cite its supporting reference 

- I grouped the Above and Below average test score categories, because students wanting to know the best path will know which group they fit into based on their own test scores. This choice makes it easier for the audience to answer their own question. Wainer, Howard (2014)
- choice, reference 

Comments from peers 

- The data structure satisfies the portfolio display requirements.
- ACT score is a continuous quantative variable, this will tell a different story when it is shown as such, not as a block category.
- Find and communicate any background or limitations on the data. Is there a specific time span, or were some observations included or not? I currently do not know these things about my college earnings data, but they are important to the story.
- Categorizing by large and small schools may be useful, but the data set does not have that data.
- Initially I thought each dot was a student, but in fact it is a college. Test scores, earnings, and need fractions represent medians for the students who attended the school.


## D2 multiway 

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc




## D3 correlations 

State the number of observations:  196

List the variables: 

- engine bore size
- engine stroke size
- vehicle body style: convertible, hardtop, batchback, sedan, wagon
- vehicle drive wheels: front and rear, 4wd eliminated because it was not well represented

State the graph type: Scatterplot

Explain why the graph type is suited to the data structure:  

- 2 quantitative varibles
- looks for correlation between them, very little in this case


Explain each design choice and cite its supporting reference 

- highlight difference between bore size, easier to see differences in the y axis

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc


## D4 injuries or fatalities displayed ethically  

**Context** 

Type of injury or fatality: deaths in motorsports

People affected: racing fans, teams

Over what span of time: the last 100 years

**Graph the data conventionally**

State the number of observations: 3446 death records over 116 years.

List the variables:

- quantitative var: count of fatalities in that year
- categorical var: time in years

State the graph type: line graph

Explain why the graph type is suited to the data structure: 

- it shows the change in numbers of deaths over time

Explain the visual-rhetoric features of the graph that make it unethical:  

- no context, just a line.
- Representing people as a yearly sum does not recognize the individual costs
- it looks strikingly close to a financial graph...

**Redesign the graph to display the data ethically**

State the new graph type (if any): still a line chart

Explain each design choice in the redesign and cite its supporting reference 

- represent each fatality as a small person. Humanizes it, from waitbutwhy
- somber color scheme

Comments from peers 

- Any suggestions on improving the ethical display of injuries or fatalities? 
- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc








## D5 redesign a graphical lie 

**The original deceptive graph**

The original image is included in the portfolio: Yes / No  

Explain the visual-rhetoric features of the graph that make it deceptive:  

- point 
- point 
- etc 

Comments from peers 

- Are there additional deceptive practices that have not been mentioned? 
- Other comments 
- etc




**The redesigned graph**

State the number of observations:  

Identify the variables:  

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure: 

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc











## D6 multivariate 

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc





## D7 self-taught  

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc  

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc




