---
output: github_document
---
## Week 6 reading prompts  

Dragga, Sam & Dan Voss (2001) Cruel pies: The inhumanity of technical
illustrations. *Technical Communication* 48(3): 265--274.

**Prompt:** Explain how the prevalent treatment of ethics in visual communication is lacking.

**Response:** All previous research and literature on ethical graphics focuses on correctly representing numerical data, and preventing misleading conclusions. Even if the graphic is true, and not misleading in any way, it can still turn the subject into nothing more than statistics.


**Prompt:** Explain the purpose of "humanizing" data displays depicting human suffering or death. 

**Response:**  As humans, we have the capacity for compassion and empathy, and those feelings have the unique ability to drive us to action. When we see a graphic about fatalities or injuries, we are meant to take away a drive to action, to improve the situation or help those affected.


**Prompt:**  Consider the authors' attempts at redesigning such data displays. Did one in particular strike you as ineffective? Explain    

**Response:** The author's redesign of Minard's depiction of Napoleons's casualties did not seem poingnant. Placing figures of soldiers and gravestones to depict the army size and casualties makes the graphic look more like a game of Risk, and not like thousands of men perishing.


**Prompt:**  Did one in particular strike you as effective? Explain. 

**Response:** The most effective humanizing redesign is Figure 11: injuries related to baby walkers. The child in the walker has a clear progression from top of stairs to ambulance, without appearing humorous or light hearted, but also not being graphic or gruesome.


## Week 4 Reading Prompts  

Wainer, Howard (2014) Fifteen displays about one thing. In: *Medical
illuminations: Using evidence, visualization, and statistical thinking to
improve healthcare.* UK: Oxford University Press, 32--49.

Definition: "Gram staining" (named after its inventor, the Danish scientist 
Hans Christian Gram) is a method of staining to distinguish one type of 
bacterium from another---it can be used as a faster substitute for culturing. 
Gram staining is a category with two levels: some bacteria are Gram stain 
negative and some are Gram stain positive. Read more about it on the  
[Gram stain Wiki](https://en.wikipedia.org/wiki/Gram_stain).  


**Prompt:** Reviewing the article carefully, come up with a list of variables. 
Classify each as quantitative or categorical, and if categorical, the levels. 

**Response:** 

variable name: Antibiotic

- type: Categorical
- levels (if categorical):  3. Penicillin, Streptomycin, Neomycin

variable name:  Bacterium

- type:    Categorical
- levels (if categorical): 16 examples of bacteria species

variable name: Minimum inhibitory concentration (MIC)

- type:    Quantitative continuous

variable name: Gram staining

- type:    Categorical
- levels (if categorical): 2: Positive and Negative

 
**Prompt:** The article title is "Fifteen displays about one thing." After 
reading the entire article, what is the "one thing?" Note that the "one thing" 
might imply multiple goals or more than one question. 

**Response:** Effectiveness of various antibiotics against a variety of bacteria.



**Prompt:** In your opinion, which of the 15 displays best answers the 
question(s) about the "one thing?"

**Response:**   Entry 10 - Adding Words


**Prompt:** Explain why.  

**Response:** For someone not deeply familiar with the concept of MIC, words pointing out the most and least effective drugs is highly informative. Grouping bacteria by Gram staining shows the slight inverse correlation between Penicillin and the other two. Connecting the dots into lines is not advised here, because the x axis is a categorical variable, and a line implies an order or trend between the types of bacteria, when there is no order or meaning to the order. No matter which convention you use (bigger is better or opposite), clearly label or show the meaning.



**Prompt:** Re-read Wainer's conclusion section. What main points does he make 
about graph design or visual rhetoric that you could apply to your own work 
this term. 

**Response:** The most effictive data display depends on the question to be answered. Seeing general trends or comparing individual numbers will result in a drastically different graph. In this class, the graph and question need to be tightly intertwined. Data displays are heavily influenced by audience analysis, and anticipating what questions they want answered by your chart.


## Week 2 Reading prompts

Tufte, Edward (1997) The decision to launch the space shuttle Challenger. 
In: *Visual and statistical thinking: Displays of evidence for making
decisions.* Cheshire, CT: Graphics Press, 16--31.

**Prompt:** Tufte says, "Regardless of the indirect cultural causes of the
accident, there was a clear proximate cause." Summarize Tufte's explanation 
of the proximate cause.  

**Response:** The engineers correctly concluded that lower temperatures cause the rubber o-rings to lose resiliency, which can potentially lead to seal failures. The evidence they presented to NASA and management was muddled with irrelevent data and unclear graphs. Unclear visual evidence misled the decision makers and did not convey the link between low temperatures and seal failures.


**Prompt:** Describe the evidence the author presents to support those ideas.

**Response:** Data from all previous launches ordered by temperature shows a clear trend in o-ring damage: colder launches resulted in more seal  damage. Tufte shows the graphs and charts presented by the engineers, which are unhelpful and bury important information.


**Prompt:** What data were used in making the decision to launch? What data 
were not used but should have been used (according to Tufte) in making the
launch decision?

**Response:** Data for blow-by was presented, which is not the failure mechanism they are interested in. Charts and tables refer to data from qualification rockets, which is not a valid comparison because those rockets are not flying. None of this data should have been used in the decision making, and it only muddied the water. Data from successful launches was not used, bue should have because it establishes an accurate comparison for flights with seal damage.


**Prompt:** On page 23, Tufte presents a graph that provides visual evidence
that the "launch was completely outside the engineering database accumulated 
in 24 previous flight." Describe the structure of this data set:

- Number of observations 
- Data structure: classify each variable as quantitative (continuous or discrete) and categorical (nominal or ordinal and number of levels). 

**Response:**  It included 23 observations (24 total flights occurred, but one rocket was not recovered). The calculated variable 'o-ring damage index' is quantitative continuous. Launch temperature is quantitative continuous data. He also included the forecasted temperature range on launch day to illustrate how far it was from proven conditions.


**Prompt:** Summarize the main thesis of the paper.  

**Response:** The Challenger launch decision was flawed by poor visual rhetoric, unclear evidence, and lacking logical analysis that obscured the intended message